name: Merge Sensor Data

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  merge-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Merge sensor files
      run: |
        python .github/scripts/merge_sensor_data.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/sensor_data_combined.csv
        git commit -m "Auto-merged sensor data [skip ci]"
        git push
