name: Merge Sensor Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  merge-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Merge sensor files
      run: |
        python .github/scripts/merge_sensor_data.py
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/sensor_data_combined.csv
        git commit -m "Auto-merged sensor data [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git


